## Quiz 1
In this quiz, you'll be working with data on the average life expectancy at birth and the average BMI for males across the world. The data comes from Gapminder.    

The data file can be found under the "bmi_and_life_expectancy.csv" tab in the quiz below. It includes three columns, containing the following data:    
* Country – The country the person was born in.
* Life expectancy – The average life expectancy at birth for a person in that country.
* BMI – The mean BMI of males in that country.    

You'll need to complete each of the following steps:
1. Load the data
The data is in the file called "bmi_and_life_expectancy.csv".
Use pandas read_csv to load the data into a dataframe (don't forget to import pandas!)
Assign the dataframe to the variable bmi_life_data.
2. Build a linear regression model
Create a regression model using scikit-learn's LinearRegression and assign it to bmi_life_model.
Fit the model to the data.
3. Predict using the model

Predict using a BMI of 21.07931 and assign it to the variable laos_life_exp.

In [1]:
import pandas as pd

bmi_life_data = pd.read_csv("bmi_and_life_expectancy.csv")
print(bmi_life_data)

                Country  Life expectancy       BMI
0           Afghanistan             52.8  20.62058
1               Albania             76.8  26.44657
2               Algeria             75.5  24.59620
3               Andorra             84.6  27.63048
4                Angola             56.7  22.25083
..                  ...              ...       ...
158             Vanuatu             63.4  26.78926
159  West Bank and Gaza             74.1  26.57750
160             Vietnam             74.1  20.91630
161              Zambia             51.1  20.68321
162            Zimbabwe             47.3  22.02660

[163 rows x 3 columns]


In [14]:
print(type(bmi_life_data[['BMI']]))
print(type(bmi_life_data['BMI']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [18]:
from sklearn.linear_model import LinearRegression

bmi_life_model = LinearRegression()
bmi_life_model.fit(bmi_life_data[['BMI']], bmi_life_data[['Life expectancy']])

laos_life_exp = bmi_life_model.predict([[21.07931]])
print(laos_life_exp)

[[60.31564716]]


## Quiz 2
In this quiz, you'll be using the Boston house-prices dataset. The dataset consists of 13 features of 506 houses and the median home value in $1000's. You'll fit a model on the 13 features to predict the value of the houses.

You'll need to complete each of the following steps:
1. Build a linear regression model
  * Create a regression model using scikit-learn's LinearRegression and assign it to model.
  * Fit the model to the data.
2. Predict using the model

Predict the value of sample_house.

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

# Load the data from the boston house-prices dataset 
boston_data = load_boston()
x = boston_data['data']
y = boston_data['target']

print(x)
print(y)

model = LinearRegression()
model.fit(x, y)

# Make a prediction using the model
sample_house = [[2.29690000e-01, 0.00000000e+00, 1.05900000e+01, 0.00000000e+00, 4.89000000e-01,
                6.32600000e+00, 5.25000000e+01, 4.35490000e+00, 4.00000000e+00, 2.77000000e+02,
                1.86000000e+01, 3.94870000e+02, 1.09700000e+01]]
# TODO: Predict housing price for the sample_house
prediction = model.predict(sample_house)
print(prediction)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

## Quiz 3
In this assignment's data.csv, you'll find data for a bunch of points including six predictor variables and one outcome variable. Use sklearn's Lasso class to fit a linear regression model to the data, while also using L1 regularization to control for model complexity.

1. Load in the data
  * The data is in the file called 'data.csv'. Note that there's no header row on this file.
  * Split the data so that the six predictor features (first six columns) are stored in X, and the outcome feature (last column) is stored in y.

In [26]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso

train_data = pd.read_csv('linear_reg_regularisation.csv', header = None)
print(train_data)

           0        1         2        3        4        5         6
0    1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590  12.31798
1   -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640  23.67628
2    5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626  -1.53459
3    0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084 -24.68670
4    5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022  17.54122
..       ...      ...       ...      ...      ...      ...       ...
95  -4.58240 -1.27825   7.55098  8.83930 -3.80318  0.04386  26.14768
96 -10.00364  2.66002  -4.26776 -3.73792 -0.72349 -0.24617   0.76214
97  -4.32624 -2.30314  -8.16044  4.46366 -3.33569 -0.01655 -10.05262
98  -1.90167 -0.15858 -10.43466  4.89762 -0.64606 -0.14519 -19.63970
99   2.43213  2.41613   2.49949 -8.03891 -1.64164 -0.63444  12.76193

[100 rows x 7 columns]


In [27]:
X = train_data.iloc[:,:-1]
print(X)

           0        1         2        3        4        5
0    1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590
1   -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640
2    5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626
3    0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084
4    5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022
..       ...      ...       ...      ...      ...      ...
95  -4.58240 -1.27825   7.55098  8.83930 -3.80318  0.04386
96 -10.00364  2.66002  -4.26776 -3.73792 -0.72349 -0.24617
97  -4.32624 -2.30314  -8.16044  4.46366 -3.33569 -0.01655
98  -1.90167 -0.15858 -10.43466  4.89762 -0.64606 -0.14519
99   2.43213  2.41613   2.49949 -8.03891 -1.64164 -0.63444

[100 rows x 6 columns]


In [28]:
y = train_data.iloc[:,-1:]
print(y)

           6
0   12.31798
1   23.67628
2   -1.53459
3  -24.68670
4   17.54122
..       ...
95  26.14768
96   0.76214
97 -10.05262
98 -19.63970
99  12.76193

[100 rows x 1 columns]


2. Fit data using linear regression with Lasso regularization
  * Create an instance of sklearn's Lasso class and assign it to the variable lasso_reg. You don't need to set any parameter values: use the default values for the quiz.
  * Use the Lasso object's .fit() method to fit the regression model onto the data.

In [29]:
lasso_reg = Lasso()
lasso_reg.fit(X, y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

3. Inspect the coefficients of the regression model
  * Obtain the coefficients of the fit regression model using the .coef_ attribute of the Lasso object. Store this in the reg_coef variable: the coefficients will be printed out, and you will use your observations to answer the question at the bottom of the page.

In [25]:
reg_coef = lasso_reg.coef_
print(reg_coef)

[ 0.          2.35793224  2.00441646 -0.05511954 -3.92808318  0.        ]


4. For which of the predictor features has the lasso regularization step zeroed the corresponding coefficient?
Answer: Column 1, 6

## Quiz 4 
Feature scaling. he only thing different for this quiz compared to the previous one is the addition of a new step after loading the data, where you will use sklearn's StandardScaler to standardize the data before you fit a linear regression model to the data with L1 (Lasso) regularization.

1. Load in the data

  * The data is in the file called 'data.csv'. Note that there's no header row on this file.
  * Split the data so that the six predictor features (first six columns) are stored in X, and the outcome feature (last column) is stored in y.

In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

train_data = pd.read_csv('linear_reg_regularisation.csv', header = None)
X = train_data.iloc[:, :-1]
y = train_data.iloc[:, -1:]

print(X)
print(y)

           0        1         2        3        4        5
0    1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590
1   -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640
2    5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626
3    0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084
4    5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022
..       ...      ...       ...      ...      ...      ...
95  -4.58240 -1.27825   7.55098  8.83930 -3.80318  0.04386
96 -10.00364  2.66002  -4.26776 -3.73792 -0.72349 -0.24617
97  -4.32624 -2.30314  -8.16044  4.46366 -3.33569 -0.01655
98  -1.90167 -0.15858 -10.43466  4.89762 -0.64606 -0.14519
99   2.43213  2.41613   2.49949 -8.03891 -1.64164 -0.63444

[100 rows x 6 columns]
           6
0   12.31798
1   23.67628
2   -1.53459
3  -24.68670
4   17.54122
..       ...
95  26.14768
96   0.76214
97 -10.05262
98 -19.63970
99  12.76193

[100 rows x 1 columns]


2. (NEW) Perform feature scaling on data via standardization

  * Create an instance of sklearn's StandardScaler and assign it to the variable scaler.
  * Compute the scaling parameters by using the .fit_transform() method on the predictor feature array, which also returns the predictor variables in their standardized values. Store those standardized values in X_scaled.

In [3]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[ 2.40939098e-01  1.29044717e+00 -1.32657695e+00  3.62755606e-01
  -1.29448250e+00  1.07584269e+00]
 [-6.89385644e-01 -1.12048023e-01  1.17210015e+00  3.90650530e-01
  -1.07641127e+00 -1.83941486e-02]
 [ 9.35271727e-01  6.72407457e-01 -1.28898654e-01  5.02949170e-01
   1.42432265e-01 -1.18481222e+00]
 [ 8.43473152e-02 -1.66990046e+00 -1.20523179e+00  5.74518932e-01
   1.77024049e-01 -4.42047548e-01]
 [ 1.07073817e+00  1.28173054e-02  2.23374324e+00  7.07750768e-01
   5.89354080e-01  1.53832915e+00]
 [-5.03547007e-01 -3.82877792e-01 -2.86704658e-01 -1.35597001e-01
  -7.32567225e-01  2.81663911e+00]
 [-1.26838661e+00  6.30722889e-02  1.29647329e+00  1.38965170e+00
   9.37562988e-02 -1.10979200e-01]
 [-1.28336432e+00  4.68559271e-01 -6.53368701e-01 -8.60174370e-01
  -8.00219905e-01 -1.26209441e+00]
 [ 1.58175014e+00  1.31910564e+00 -2.33513254e+00 -9.56289301e-01
  -8.29972817e-01 -5.31231964e-01]
 [-1.07677452e+00 -2.30532033e+00  4.19813395e-01 -6.63656674e-01
   6.74354734e-01  9.1859

3. Fit data using linear regression with Lasso regularization
  * Create an instance of sklearn's Lasso class and assign it to the variable lasso_reg. You don't need to set any parameter values: use the default values for the quiz.
  * Use the Lasso object's .fit() method to fit the regression model onto the data. Make sure that you apply the fit to the standardized data from the previous step (X_scaled), not the original data.

In [5]:
lasso_reg = Lasso()
lasso_reg.fit(X_scaled, y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

4. Inspect the coefficients of the regression model

  * Obtain the coefficients of the fit regression model using the .coef_ attribute of the Lasso object. Store this in the reg_coef variable: the coefficients will be printed out, and you will use your observations to answer the question at the bottom of the page.

In [9]:
reg_coef = lasso_reg.coef_
print(reg_coef)

# Expected coefficients
# [  0.           3.90753617   9.02575748  -0.         -11.78303187
#   0.45340137]

[  0.           3.90753617   9.02575748  -0.         -11.78303187
   0.45340137]
